resources:
  - name: ruby-image
    type: registry-image
    source:
      repository: mirror.gcr.io/ruby
      tag: "3.0.0"
  - name: ops-git
    type: git
    source:
      uri: https://github.com/barrucadu/ops.git
  - name: github-git
    type: git
    source:
      uri: https://github.com/barrucadu/ops.git
      paths:
        - github/
  - name: every-day
    type: time
    source:
      interval: 24h

jobs:
  - name: update-pipeline
    plan:
      - get: ops-git
        trigger: true
      - set_pipeline: github
        file: ops-git/concourse/pipelines/github.yml

  - name: configure-repos
    serial: true
    plan:
      - get: ruby-image
      - get: every-day
        trigger: true
      - get: github-git
        trigger: true
      - task: configure-repos
        image: ruby-image
        config:
          platform: linux
          inputs:
            - name: github-git
          params:
            GITHUB_TOKEN: ((github-token))
          run:
            dir: github-git/github
            path: sh
            args:
              - -ce
              - |
                bundle
                bundle exec rake github:configure
