name: Run tests

"on": pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Lint (resources)
        run: |
          set -ex
          pip install flake8 black
          black -l 100 concourse/{feed,rsync}-resource/src/{check,in,out}
          flake8 --max-line-length 100 concourse/{feed,rsync}-resource/src/{check,in,out}
          git diff --exit-code
      - name: Lint (github)
        run: |
          cd github
          bundle
          bundle exec rubocop
      - name: Lint (yaml)
        run: |
          set -ex
          pip install yamllint
          yamllint -s .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - name: Check Dependencies (feed-resource)
        run: |
          cd concourse/feed-resource
          pip install -r requirements-freeze.txt
      - name: Check Configuration and Dependencies (octodns)
        run: |
          cd dns
          pip install -r requirements-freeze.txt
          export AWS_ACCESS_KEY_ID=dummy
          export AWS_SECRET_ACCESS_KEY=dummy
          octodns-validate --config-file dns.yaml
      - name: Check Configuration (terraform)
        uses: dflook/terraform-validate@v1
        with:
          path: aws
